CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(50) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `accounts` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `region` VARCHAR(50) NOT NULL UNIQUE,
  `unit_name` VARCHAR(100) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `query_records` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT NOT NULL,
  `region` VARCHAR(50) NOT NULL,
  `query_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `data` TEXT,
  `status` VARCHAR(20) DEFAULT 'pending',
  `message` VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `submissions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT NOT NULL,
  `region` VARCHAR(50) NOT NULL,
  `form_data` TEXT NOT NULL,
  `submit_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `response` TEXT,
  `status` VARCHAR(20) DEFAULT 'pending',
  FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON DELETE CASCADE
);